require "rest-client"
require "json"
require "json-schema"

require "objectia/version"
require "objectia/errors/api_error"
require "objectia/errors/api_connection_error"
require "objectia/errors/api_timeout_error"
require "objectia/errors/response_error"
require "objectia/rest"
require "objectia/multipart"
require "objectia/usage_api"
require "objectia/geoip_api"
require "objectia/mail_api"
require "objectia/client"

